services:
  web:
    image: orsee:${ORSEE_VERSION_TAG}
    build:
      context: ./web
      args:
        ROOT_DIRECTORY: ${ROOT_DIRECTORY:-/orsee}
        ORSEE_VERSION_TAG: ${ORSEE_VERSION_TAG}
    ports:
      - 8080:80
    env_file:
      - .env
    read_only: true
    tmpfs:
      - /run
      - /var/cache
      - /var/local
  db:
    image: mariadb:12.2
    volumes:
      - db:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file:
      - .env
  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
    profiles:
      - test
volumes:
  db: